from __future__ import annotations

from typing import Any

import yaml

from skillforge.models import SkillManifest, StepConfig, TriggerConfig

_PYTHON_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"
{name} — {description}
Generated by skillforge. Edit freely.
\"\"\"
from __future__ import annotations

import os
import sys


def run() -> None:
    \"\"\"Execute all workflow steps.\"\"\"
{steps_code}

if __name__ == "__main__":
    run()
"""

_STEP_TEMPLATES: dict[str, str] = {
    "claude": """\
    # Step: {name}
    import anthropic
    _client = anthropic.Anthropic()
    _resp = _client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[{{"role": "user", "content": f"{prompt}"}}],
    )
    {output} = _resp.content[0].text if _resp.content else ""
""",
    "github": """\
    # Step: {name}
    import subprocess as _sp
    _result = _sp.run(["gh", "{action}"], capture_output=True, text=True, check=True)
    {output} = _result.stdout
""",
    "slack": """\
    # Step: {name}
    import urllib.request, json as _json
    _webhook = os.environ["SLACK_WEBHOOK_URL"]
    _payload = _json.dumps({inputs}).encode()
    urllib.request.urlopen(urllib.request.Request(_webhook, _payload,
        {{"Content-Type": "application/json"}}))
""",
    "http": """\
    # Step: {name}
    import urllib.request
    _resp = urllib.request.urlopen("{action}")
    {output} = _resp.read().decode()
""",
    "shell": """\
    # Step: {name}
    import subprocess as _sp
    _result = _sp.run("{action}", shell=True, capture_output=True, text=True)
    {output} = _result.stdout
""",
}


def manifest_to_yaml(manifest: SkillManifest) -> str:
    data: dict[str, Any] = {
        "name": manifest.name,
        "description": manifest.description,
        "version": manifest.version,
        "trigger": {
            "type": manifest.trigger.type,
            "schedule": manifest.trigger.schedule,
            "endpoint": manifest.trigger.endpoint,
        },
        "steps": [
            {
                "name": s.name,
                "tool": s.tool,
                "action": s.action,
                "prompt": s.prompt,
                "inputs": s.inputs,
                "output": s.output,
            }
            for s in manifest.steps
        ],
    }
    return yaml.dump(data, sort_keys=False, allow_unicode=True)


def yaml_to_manifest(yaml_str: str) -> SkillManifest:
    data: dict[str, Any] = yaml.safe_load(yaml_str)
    trigger_data = data.get("trigger", {})
    trigger = TriggerConfig(
        type=trigger_data.get("type", "manual"),
        schedule=trigger_data.get("schedule", ""),
        endpoint=trigger_data.get("endpoint", ""),
    )
    steps = [
        StepConfig(
            name=s.get("name", ""),
            tool=s.get("tool", ""),
            action=s.get("action", ""),
            prompt=s.get("prompt", ""),
            inputs=s.get("inputs", {}),
            output=s.get("output", ""),
        )
        for s in data.get("steps", [])
    ]
    return SkillManifest(
        name=data.get("name", ""),
        description=data.get("description", ""),
        trigger=trigger,
        steps=steps,
        version=str(data.get("version", "1.0")),
    )


def manifest_to_python(manifest: SkillManifest) -> str:
    steps_lines = []
    for step in manifest.steps:
        template = _STEP_TEMPLATES.get(
            step.tool, "    # Step: {name} (unknown tool)\n    pass\n"
        )
        output_var = step.output or "_output"
        rendered = template.format(
            name=step.name,
            action=step.action,
            prompt=step.prompt,
            output=output_var,
            inputs=repr(step.inputs),
        )
        steps_lines.append(rendered)

    steps_code = "\n".join(steps_lines) if steps_lines else "    pass"
    return _PYTHON_TEMPLATE.format(
        name=manifest.name,
        description=manifest.description,
        steps_code=steps_code,
    )
